#!/usr/bin/env bash
#
# sync_shared_ios.sh — copy the Hora-family shared Swift source from the local hora-core
# checkout into Varisankya, rewriting the "__HORA_APP_NAME__" display-name token.
#
# Synced files are GENERATED copies. Do NOT hand-edit them in this app — edit the canonical
# version in hora-core/shared/ios/swift/ and re-run this script. (Mirrors the Android sync.)
#
# Run from the Varisankya repo root:  bash ios/tools/sync_shared_ios.sh
#
set -euo pipefail

# 1) Local hora-core checkout (override per machine with the HORA_CORE env var).
HORA_CORE="${HORA_CORE:-C:/Users/Aarsh/Source/hora-core/hora-core}"

# 2) This app's user-facing display name — the "__HORA_APP_NAME__" token is rewritten to this.
APP_NAME="${APP_NAME:-Varisankya}"

# 3) This app's iOS source root (the folder that holds Services/, Views/, …).
IOS_APP_ROOT="${IOS_APP_ROOT:-ios/Varisankya}"
# Provenance manifest — kept OUT of the source root so it is never compiled into the app.
MANIFEST="${MANIFEST:-ios/tools/.hora-core-synced-ios}"

src_root="$HORA_CORE/shared/ios/swift"
[ -d "$src_root" ] || { echo "error: shared iOS source not found at $src_root" >&2; exit 1; }

# canonical-file : destination-relative-to-IOS_APP_ROOT
FILES=(
  "Haptics.swift:Services/Haptics.swift"
  "BiometricAuth.swift:Services/BiometricAuth.swift"
  "SelectionSheet.swift:Views/SelectionSheet.swift"
)

mkdir -p "$(dirname "$MANIFEST")"
{
  echo "# Generated by sync_shared_ios.sh — do not hand-edit the files listed below."
  echo "# Edit them in hora-core/shared/ios/swift/ and re-run this script."
  echo "# source: $src_root"
  echo "# app: $APP_NAME"
  echo "# synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if commit=$(git -C "$HORA_CORE" rev-parse --short HEAD 2>/dev/null); then
    echo "# hora-core commit: $commit"
  fi
  echo "#"
} > "$MANIFEST"

for entry in "${FILES[@]}"; do
  name="${entry%%:*}"
  rel_dest="${entry##*:}"
  s="$src_root/$name"
  d="$IOS_APP_ROOT/$rel_dest"
  if [ ! -f "$s" ]; then
    echo "warning: '$name' not found in hora-core — skipping" >&2
    continue
  fi
  mkdir -p "$(dirname "$d")"
  sed "s/__HORA_APP_NAME__/$APP_NAME/g" "$s" > "$d"
  echo "$rel_dest" >> "$MANIFEST"
  echo "synced: $rel_dest"
done

echo "Done -> $IOS_APP_ROOT (generated; edit shared Swift in hora-core, then re-run)."
