"use client";

/*
 * GENERATED BY web/scripts/sync_shared_web.sh — DO NOT HAND-EDIT.
 * Sourced from: shared/web/components/ServiceWorker.tsx
 * Synced: 2026-06-27T23:26:03Z
 * hora-core commit: 8490541
 */

import { useEffect } from "react";

/**
 * Registers the offline-shell service worker once, on the client, in production.
 * Hora family shared component — canonical in hora-core/shared/web/components/.
 */
export function ServiceWorker() {
  useEffect(() => {
    if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
    if (process.env.NODE_ENV !== "production") return;
    const onLoad = () => navigator.serviceWorker.register("/sw.js").catch(() => {});
    window.addEventListener("load", onLoad);
    return () => window.removeEventListener("load", onLoad);
  }, []);
  return null;
}
