// Generates the Material 3 tonal palette for the web app, seeded from the
// Varisankya brand icon colour (the "വരി" teal-green). This mirrors how Android's
// Material You builds a palette from a source colour — except the web has no
// wallpaper to read, so we seed from the brand icon instead, giving every user
// the same on-brand M3 scheme.
//
// Re-run after changing SEED:  node scripts/gen-theme.mjs
// Output: app/theme.css (generated; do not hand-edit).

import {
  argbFromHex,
  hexFromArgb,
  Hct,
  SchemeTonalSpot,
  MaterialDynamicColors,
} from "@material/material-color-utilities";
import { writeFileSync } from "node:fs";

const SEED = "#465454"; // sampled from public/icons/icon-512.png (brand text colour)

// The full set of M3 system colour roles we expose as CSS variables.
const ROLES = [
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "background", "onBackground",
  "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
  "surfaceDim", "surfaceBright",
  "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
  "surfaceContainerHigh", "surfaceContainerHighest",
  "outline", "outlineVariant",
  "inverseSurface", "inverseOnSurface", "inversePrimary",
  "scrim", "shadow",
];

const mdc = MaterialDynamicColors;
const kebab = (s) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());

function vars(scheme) {
  return ROLES.map((r) => {
    const dc = mdc[r];
    if (!dc || typeof dc.getArgb !== "function") return null;
    return `  --md-${kebab(r)}: ${hexFromArgb(dc.getArgb(scheme))};`;
  })
    .filter(Boolean)
    .join("\n");
}

const seed = Hct.fromInt(argbFromHex(SEED));
const light = vars(new SchemeTonalSpot(seed, false, 0));
const dark = vars(new SchemeTonalSpot(seed, true, 0));

const css = `/* GENERATED by scripts/gen-theme.mjs — Material 3 tonal palette seeded from the
 * Varisankya brand icon (${SEED}). Re-run \`node scripts/gen-theme.mjs\` to
 * regenerate. Do not edit by hand. */
:root {
${light}
}
:root[data-theme="dark"] {
${dark}
}
@media (prefers-color-scheme: dark) {
  :root[data-theme="system"] {
${dark}
  }
}
`;

writeFileSync(new URL("../app/theme.css", import.meta.url), css);
console.log(css);
console.error("✓ wrote app/theme.css");
