// Generates the Material 3 tonal palette for the web app.
//
// Hora family web design language: **neutral surfaces + per-app accent**. The
// accent roles (primary/secondary/tertiary/error + their on/container variants)
// come from a SchemeTonalSpot seeded from the Varisankya brand icon colour (the
// "വരി" teal), keeping the app's identity. The surface / background / outline /
// neutral roles come from a SchemeNeutral (near-zero chroma) so the chrome reads
// as a clean neutral dark — matching the rest of the family instead of being
// tinted toward the seed. Each Hora app keeps its own accent; only the surfaces
// are held neutral and consistent.
//
// Re-run after changing SEED:  node scripts/gen-theme-run.mjs
// Output: app/theme.css (generated; do not hand-edit).

import {
  argbFromHex,
  hexFromArgb,
  Hct,
  SchemeTonalSpot,
  SchemeNeutral,
  MaterialDynamicColors,
} from "@material/material-color-utilities";
import { writeFileSync } from "node:fs";

const SEED = "#465454"; // sampled from public/icons/icon-512.png (brand text colour)

// The full set of M3 system colour roles we expose as CSS variables.
const ROLES = [
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "background", "onBackground",
  "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
  "surfaceDim", "surfaceBright",
  "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
  "surfaceContainerHigh", "surfaceContainerHighest",
  "outline", "outlineVariant",
  "inverseSurface", "inverseOnSurface", "inversePrimary",
  "scrim", "shadow",
];

// Roles drawn from the *accent* scheme (vivid, seed-tinted). Everything else —
// backgrounds, surfaces, outlines, inverse surfaces, scrim/shadow — is drawn
// from the *neutral* scheme so the chrome stays a clean neutral dark.
const ACCENT_ROLES = new Set([
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "inversePrimary",
]);

const mdc = MaterialDynamicColors;
const kebab = (s) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());

function vars(accent, neutral) {
  return ROLES.map((r) => {
    const dc = mdc[r];
    if (!dc || typeof dc.getArgb !== "function") return null;
    const scheme = ACCENT_ROLES.has(r) ? accent : neutral;
    return `  --md-${kebab(r)}: ${hexFromArgb(dc.getArgb(scheme))};`;
  })
    .filter(Boolean)
    .join("\n");
}

const seed = Hct.fromInt(argbFromHex(SEED));
const light = vars(
  new SchemeTonalSpot(seed, false, 0),
  new SchemeNeutral(seed, false, 0),
);
const dark = vars(
  new SchemeTonalSpot(seed, true, 0),
  new SchemeNeutral(seed, true, 0),
);

const css = `/* GENERATED by scripts/gen-theme.mjs — Material 3 palette: teal accent (seeded
 * from the Varisankya brand icon ${SEED}) over neutral surfaces (Hora family
 * web design language). Re-run \`node scripts/gen-theme-run.mjs\` to regenerate.
 * Do not edit by hand. */
:root {
${light}
}
:root[data-theme="dark"] {
${dark}
}
@media (prefers-color-scheme: dark) {
  :root[data-theme="system"] {
${dark}
  }
}
`;

writeFileSync(new URL("../app/theme.css", import.meta.url), css);
console.log(css);
console.error("✓ wrote app/theme.css");
