#!/usr/bin/env bash
#
# sync_shared_web.sh — copy shared Web UI stylesheets from the local hora-core checkout
# into the Next.js app.
#
# Synced files are GENERATED copies. Do NOT hand-edit them in the app — edit the canonical
# version in hora-core/shared/web/res/css/ and re-run this script.
#
# Run from the app's repo root:  bash web/scripts/sync_shared_web.sh
#
set -euo pipefail

# 1) Local hora-core checkout (override per machine with the HORA_CORE env var).
HORA_CORE="${HORA_CORE:-C:/Users/Aarsh/Source/hora-core/hora-core}"

# 2) This app's stylesheet destination root.
WEB_APP_ROOT="${WEB_APP_ROOT:-web/app}"

src="$HORA_CORE/shared/web/res/css/web_shared.css"
[ -f "$src" ] || { echo "error: shared web style not found at $src" >&2; exit 1; }

dest="$WEB_APP_ROOT/web_shared.css"
mkdir -p "$(dirname "$dest")"
cp "$src" "$dest"

# Write provenance header locally at the top of the synced file
temp_file=$(mktemp)
{
  echo "/*"
  echo " * GENERATED BY sync_shared_web.sh — DO NOT HAND-EDIT."
  echo " * Sourced from: shared/web/res/css/web_shared.css"
  echo " * Synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if commit=$(git -C "$HORA_CORE" rev-parse --short HEAD 2>/dev/null); then
    echo " * hora-core commit: $commit"
  fi
  echo " */"
  echo ""
  cat "$dest"
} > "$temp_file"
mv "$temp_file" "$dest"

echo "Done. Shared Web styles synced from hora-core to $dest (generated; edit in hora-core, then re-run)."
