#!/usr/bin/env bash
#
# sync_shared_web.sh — Varisankya copy. Customised from hora-core's shared/web layer.
# Copies the shared Web design system (CSS) and components from the local hora-core
# checkout into the Next.js app, prepending a generated-file header and recording a
# provenance manifest.
#
# Synced files are GENERATED copies. Do NOT hand-edit them — edit the canonical version
# in hora-core/shared/web/ and re-run this script.
#
# Run from the repo root:  bash web/scripts/sync_shared_web.sh
#
set -euo pipefail

# 1) Local hora-core checkout (override per machine with the HORA_CORE env var).
HORA_CORE="${HORA_CORE:-C:/Users/Aarsh/Source/hora-core/hora-core}"

# 2) Varisankya's display name — the "__HORA_APP_NAME__" token (if any) is rewritten to this.
APP_NAME="${APP_NAME:-Varisankya}"

# 3) Varisankya's web root + provenance manifest.
WEB_APP_ROOT="${WEB_APP_ROOT:-web}"
MANIFEST="${MANIFEST:-web/.hora-core-synced-web}"

src_root="$HORA_CORE/shared/web"
[ -d "$src_root" ] || { echo "error: shared web source not found at $src_root" >&2; exit 1; }

# canonical-file (relative to shared/web) : destination (relative to WEB_APP_ROOT)
FILES=(
  "res/css/web_shared.css:app/web_shared.css"
  "components/ServiceWorker.tsx:components/ServiceWorker.tsx"
  "components/Sheet.tsx:components/Sheet.tsx"
  "components/controls.tsx:components/controls.tsx"
  "components/SignIn.tsx:components/SignIn.tsx"
  "components/ConfirmDialog.tsx:components/ConfirmDialog.tsx"
  "components/AboutSheet.tsx:components/AboutSheet.tsx"
  "components/settings.tsx:components/settings.tsx"
  "components/EmptyState.tsx:components/EmptyState.tsx"
  "components/ScreenHeader.tsx:components/ScreenHeader.tsx"
  "components/AppBar.tsx:components/AppBar.tsx"
  "components/Fab.tsx:components/Fab.tsx"
  "lib/haptics-core.ts:lib/haptics-core.ts"
  "res/theme-palette.mjs:scripts/theme-palette.mjs"
)

commit="$(git -C "$HORA_CORE" rev-parse --short HEAD 2>/dev/null || echo unknown)"
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

mkdir -p "$(dirname "$MANIFEST")"
{
  echo "# Generated by web/scripts/sync_shared_web.sh — do not hand-edit the files listed below."
  echo "# Edit them in hora-core/shared/web/ and re-run this script."
  echo "# source: $src_root"
  echo "# app: $APP_NAME"
  echo "# synced: $now"
  echo "# hora-core commit: $commit"
  echo "#"
} > "$MANIFEST"

# Emit the /* GENERATED */ provenance header (valid in both CSS and TS/TSX).
emit_header() {
  local rel_src="$1"
  echo "/*"
  echo " * GENERATED BY web/scripts/sync_shared_web.sh — DO NOT HAND-EDIT."
  echo " * Sourced from: shared/web/$rel_src"
  echo " * Synced: $now"
  echo " * hora-core commit: $commit"
  echo " */"
}

for entry in "${FILES[@]}"; do
  rel_src="${entry%%:*}"
  rel_dest="${entry##*:}"
  s="$src_root/$rel_src"
  d="$WEB_APP_ROOT/$rel_dest"
  if [ ! -f "$s" ]; then
    echo "warning: '$rel_src' not found in hora-core — skipping" >&2
    continue
  fi
  mkdir -p "$(dirname "$d")"
  tmp="$(mktemp)"
  first_line="$(head -1 "$s")"
  if printf '%s' "$first_line" | grep -qE "^[[:space:]]*[\"']use (client|server)[\"'];?[[:space:]]*$"; then
    # Keep the React directive on line 1 (must precede all other code); header after it.
    {
      echo "$first_line"
      echo ""
      emit_header "$rel_src"
      tail -n +2 "$s" | sed "s/__HORA_APP_NAME__/$APP_NAME/g"
    } > "$tmp"
  else
    {
      emit_header "$rel_src"
      sed "s/__HORA_APP_NAME__/$APP_NAME/g" "$s"
    } > "$tmp"
  fi
  mv "$tmp" "$d"
  echo "$rel_dest" >> "$MANIFEST"
  echo "synced: $rel_dest"
done

echo "Done -> $WEB_APP_ROOT (generated; edit shared web source in hora-core, then re-run)."
