#!/usr/bin/env python3
"""Hora-family notification icon generator.

Standard: a SOLID round (filled white disc) with the app's Malayalam initial
knocked out as a hollow (negative space), via a single evenOdd path. Android
tints small icons, so the art is plain white-on-transparent.

Per app, swap GLYPH_PATH for that app's Malayalam initial silhouette, centred
on (12,12) in a 24x24 viewport. Varisankya = "വ" (va).

Usage:
  python gen_notification_icon.py preview          # writes preview HTML (all scales)
  python gen_notification_icon.py emit 0.85        # writes ic_notification.xml at scale
"""
import re, sys, os

# --- Hora-family "വ" silhouette (the established Varisankya initial), centred on (12,12).
GLYPH_PATH = ("M 13.712,12.168 C 13.712,11.554 13.624,10.990 13.456,10.478 C 13.280,9.959 "
"13.032,9.513 12.710,9.132 C 12.388,8.752 11.993,8.459 11.532,8.247 C 11.064,8.035 10.544,7.932 "
"9.959,7.932 C 9.374,7.932 8.847,8.035 8.386,8.247 C 7.918,8.459 7.523,8.752 7.201,9.132 C "
"6.879,9.513 6.638,9.959 6.462,10.478 C 6.286,10.990 6.206,11.554 6.206,12.168 C 6.206,12.549 "
"6.228,12.914 6.279,13.266 C 6.330,13.617 6.418,13.968 6.535,14.326 C 6.659,14.685 6.820,15.065 "
"7.033,15.453 C 7.237,15.848 7.501,16.272 7.808,16.748 L 6.762,17.121 C 6.169,16.272 5.738,15.438 "
"5.467,14.619 C 5.189,13.800 5.050,12.958 5.050,12.102 C 5.050,11.283 5.174,10.544 5.430,9.900 C "
"5.686,9.249 6.038,8.701 6.484,8.254 C 6.930,7.808 7.457,7.472 8.064,7.230 C 8.671,6.996 9.330,6.879 "
"10.032,6.879 C 10.698,6.879 11.327,6.989 11.912,7.223 C 12.497,7.450 13.010,7.786 13.449,8.225 C "
"13.887,8.671 14.231,9.213 14.487,9.864 C 14.736,10.515 14.868,11.261 14.868,12.102 C 14.868,12.432 "
"14.839,12.768 14.787,13.112 C 14.729,13.463 14.656,13.800 14.561,14.129 C 14.465,14.458 14.348,14.780 "
"14.209,15.087 C 14.078,15.395 13.924,15.673 13.763,15.929 L 17.816,15.929 L 17.816,7.055 L 18.950,7.055 "
"L 18.950,16.945 L 12.410,16.945 L 12.410,16.265 C 12.658,15.870 12.863,15.490 13.032,15.138 C "
"13.200,14.780 13.331,14.436 13.434,14.107 C 13.536,13.778 13.609,13.456 13.646,13.134 C 13.690,12.819 "
"13.712,12.497 13.712,12.168 Z")

CX = CY = 12.0
RADIUS = 11.0  # disc radius in the 24x24 viewport (1px optical margin)
# Solid-disc circle as a path so it composes with the glyph under one evenOdd fill.
CIRCLE = f"M{CX-RADIUS},{CY} a{RADIUS},{RADIUS} 0 1,0 {2*RADIUS},0 a{RADIUS},{RADIUS} 0 1,0 {-2*RADIUS},0 Z"


def scale_glyph(path, s, cx=CX, cy=CY):
    """Scale every absolute coordinate pair around (cx,cy). The glyph uses only
    M/L/C/Z commands, all taking absolute point pairs, so a uniform pair
    transform is exact."""
    out, pending = [], []
    for t in re.findall(r'[MLCZ]|-?\d+\.?\d*', path):
        if t in 'MLCZ':
            out.append(t)
        else:
            pending.append(float(t))
            if len(pending) == 2:
                x = round(cx + (pending[0] - cx) * s, 3)
                y = round(cy + (pending[1] - cy) * s, 3)
                out.append(f"{x},{y}")
                pending = []
    return ' '.join(out)


def combined(s):
    """Disc + knocked-out glyph as one pathData string (rendered with evenOdd)."""
    return f"{CIRCLE} {scale_glyph(GLYPH_PATH, s)}"


def vector_xml(s):
    return f'''<!-- Notification status-bar icon — Hora-family standard: a SOLID round with
     the app's Malayalam initial ("വ" va for Varisankya) knocked out as a hollow.
     Android tints small icons, so this is plain white-on-transparent. One evenOdd
     path = filled disc minus the glyph. Generated by android/tools/gen_notification_icon.py
     (glyph scale {s}). Pathivu and other siblings reuse this with their own initial. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp"
    android:viewportWidth="24" android:viewportHeight="24">
    <path android:fillColor="#FFFFFF" android:fillType="evenOdd"
        android:pathData="{combined(s)}" />
</vector>
'''


def svg(s, size=120):
    return (f'<svg width="{size}" height="{size}" viewBox="0 0 24 24" '
            f'xmlns="http://www.w3.org/2000/svg"><path fill="#FFFFFF" '
            f'fill-rule="evenodd" d="{combined(s)}"/></svg>')


def preview_html(scales):
    cells = "".join(f'''<div class="col">
  <div class="label">scale {s}</div>
  <div class="bar">{svg(s)}</div>
  <div class="card">{svg(s)}</div>
  <div class="bar small">{svg(s, 36)}</div>
</div>''' for s in scales)
    return f'''<!doctype html><meta charset="utf-8"><style>
 body{{background:#202124;font-family:system-ui;margin:0;padding:24px;color:#ddd}}
 .row{{display:flex;gap:28px}} .col{{text-align:center}}
 .label{{margin-bottom:8px;font-size:13px;color:#9aa0a6}}
 .bar{{background:#0b0b0c;padding:16px;border-radius:10px}} .bar svg path{{fill:#fff}}
 .card{{background:#f1f3f4;padding:16px;border-radius:10px;margin-top:10px}} .card svg path{{fill:#1f1f1f}}
 .small{{margin-top:10px;display:inline-block}} h2{{font-weight:500;color:#e8eaed}}
</style><h2>Hora notification icon — solid disc + hollow വ (status bar / shade / 36px)</h2>
<div class="row">{cells}</div>'''


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "preview"
    here = os.path.dirname(os.path.abspath(__file__))
    if cmd == "preview":
        scales = [float(x) for x in sys.argv[2:]] or [1.0, 0.85, 0.72]
        out = os.path.abspath(os.path.join(here, "..", "..", "notif_icon_preview.html"))
        with open(out, "w", encoding="utf-8") as f:
            f.write(preview_html(scales))
        print("wrote", out, "scales", scales)
    elif cmd == "emit":
        s = float(sys.argv[2])
        dst = os.path.abspath(os.path.join(here, "..", "app", "src", "main", "res", "drawable", "ic_notification.xml"))
        with open(dst, "w", encoding="utf-8") as f:
            f.write(vector_xml(s))
        print("wrote", dst, "scale", s)
