#!/usr/bin/env bash
#
# sync_shared_android.sh — copy the Hora-family shared Android source + resources from the
# local hora-core checkout into Varisankya, rewriting the Kotlin package placeholder.
#
# Synced files are GENERATED copies. Do NOT hand-edit them in this app — edit the canonical
# version in hora-core/shared/android/ and re-run this script. (Mirrors sync_shared_skills.sh.)
#
# Run from the Varisankya repo root:  bash android/tools/sync_shared_android.sh
#
set -euo pipefail

# 1) Local hora-core checkout (override per machine with the HORA_CORE env var).
HORA_CORE="${HORA_CORE:-C:/Users/Aarsh/Source/hora-core/hora-core}"

# 2) This app's base package — the Kotlin "__HORA_PKG__" token is rewritten to this.
APP_PKG="${APP_PKG:-com.hora.varisankya}"

# 3) This app's source roots (relative to repo root, or absolute).
JAVA_ROOT="${JAVA_ROOT:-android/app/src/main/java}"
RES_ROOT="${RES_ROOT:-android/app/src/main/res}"
# Provenance manifest — kept OUT of res/ and java/ so it is never compiled.
MANIFEST="${MANIFEST:-android/tools/.hora-core-synced-android}"

src="$HORA_CORE/shared/android"
[ -d "$src" ] || { echo "error: shared android source not found at $src" >&2; exit 1; }
pkg_path="$(echo "$APP_PKG" | tr '.' '/')"

# Resources — package-independent, copied verbatim.
RES_FILES=(
  values/dimens.xml
  values/type.xml
  values/styles_shared.xml
  values/colors.xml
  values/ids.xml
  values/attrs.xml
  color/chip_background_color.xml
  color/chip_text_color.xml
  color/chip_stroke_color.xml
  color/chip_stroke_app.xml
  color/outline_stroke_app.xml
  anim/slide_in_left.xml
  anim/slide_in_right.xml
  anim/slide_out_left.xml
  anim/slide_out_right.xml
  values-night/colors.xml
  font/google_sans_flex.xml
  font/google_sans_flex_variable.ttf
  xml/backup_rules.xml
  xml/data_extraction_rules.xml
  drawable/background_pill_secondary.xml
  drawable/cursor_rounded_fat.xml
  drawable/shape_circle_dot.xml
  drawable/shape_circle_error_container.xml
  drawable/shape_rounded_line.xml
  drawable/ic_add.xml
  drawable/ic_back.xml
  drawable/ic_check.xml
  drawable/ic_check_circle.xml
  drawable/ic_chevron_right.xml
  drawable/ic_close.xml
  drawable/ic_delete.xml
  drawable/ic_delete_sweep.xml
  drawable/ic_edit.xml
  drawable/ic_google_logo.xml
  drawable/ic_history.xml
  drawable/ic_list.xml
  drawable/ic_open_in_new.xml
  drawable/ic_pause.xml
  drawable/ic_power.xml
  drawable/ic_search.xml
  drawable/ic_settings.xml
  drawable/ic_show_chart.xml
  layout/bottom_sheet_selection.xml
  layout/bottom_sheet_about.xml
  layout/bottom_sheet_confirmation.xml
)

# Kotlin utils — the "__HORA_PKG__" placeholder is rewritten to $APP_PKG.
KT_FILES=(
  util/ChipHelper.kt
  util/ThemeHelper.kt
  util/AnimationHelper.kt
  util/TimeProvider.kt
  util/BiometricAuthManager.kt
  util/DragReorderCallback.kt
  util/SwipeHelpers.kt
  BaseActivity.kt
  SelectionBottomSheet.kt
  AboutBottomSheet.kt
  ConfirmationBottomSheet.kt
  PillProgressView.kt
)

{
  echo "# Generated by sync_shared_android.sh — do not hand-edit the files listed below."
  echo "# Edit them in hora-core/shared/android/ and re-run this script."
  echo "# source: $src"
  echo "# app package: $APP_PKG"
  echo "# synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if commit=$(git -C "$HORA_CORE" rev-parse --short HEAD 2>/dev/null); then
    echo "# hora-core commit: $commit"
  fi
  echo "#"
} > "$MANIFEST"

for f in "${RES_FILES[@]}"; do
  s="$src/res/$f"; d="$RES_ROOT/$f"
  if [ ! -f "$s" ]; then echo "warning: missing $s — skipping" >&2; continue; fi
  mkdir -p "$(dirname "$d")"
  cp "$s" "$d"
  echo "res/$f" >> "$MANIFEST"
  echo "synced (res): $f"
done

for f in "${KT_FILES[@]}"; do
  s="$src/kotlin/$f"; d="$JAVA_ROOT/$pkg_path/$f"
  if [ ! -f "$s" ]; then echo "warning: missing $s — skipping" >&2; continue; fi
  mkdir -p "$(dirname "$d")"
  sed "s/__HORA_PKG__/$APP_PKG/g" "$s" > "$d"
  echo "java/$pkg_path/$f" >> "$MANIFEST"
  echo "synced (kt): $f -> $APP_PKG"
done

echo "Done. Shared Android source synced from hora-core (generated; edit in hora-core, then re-run)."
