#!/usr/bin/env bash
#
# sync_shared_skills.sh — copy shared skills from the local hora-core checkout
# into Varisankya's skill directory.
#
# Synced skills are GENERATED copies. Do NOT hand-edit them in this app — edit the
# canonical version in hora-core/.github/skills/ and re-run this script. This is the
# family's chosen consumption mechanism for shared skills (see hora-core
# docs/conventions.md → "Agent skills").
#
# DEST below is repo-root-relative, so run this from the Varisankya repo root:
#   bash android/tools/sync_shared_skills.sh
#
set -euo pipefail

# 1) Path to the local hora-core checkout (override per machine with the HORA_CORE env var).
HORA_CORE="${HORA_CORE:-C:/Users/Aarsh/Source/hora-core}"

# 2) This app's skill directory, relative to repo root or absolute.
#    Pathivu: android/.claude/skills   ·   Varisankya: android/.agent/skills
DEST="${DEST:-android/.agent/skills}"

# 3) The shared skills this app actually consumes (each must exist in hora-core).
#    NOTE: bitwarden-secrets is intentionally NOT here — Varisankya keeps its own
#    app-specific runbook (real vault item/field names) local; hora-bitwarden-secrets
#    is the scrubbed public method and is not a substitute for it.
SKILLS=(
  agent-session-closing
  agent-skill-standards
  hora-app-release
  hora-play-store
)

src_root="$HORA_CORE/.github/skills"
[ -d "$src_root" ] || { echo "error: hora-core skills not found at $src_root" >&2; exit 1; }
mkdir -p "$DEST"

manifest="$DEST/.hora-core-synced"
{
  echo "# Generated by sync_shared_skills.sh — do not hand-edit the skills listed below."
  echo "# Edit them in hora-core/.github/skills/ and re-run this script."
  echo "# source: $src_root"
  echo "# synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if commit=$(git -C "$HORA_CORE" rev-parse --short HEAD 2>/dev/null); then
    echo "# hora-core commit: $commit"
  fi
  echo "#"
} > "$manifest"

for s in "${SKILLS[@]}"; do
  src="$src_root/$s"
  if [ ! -d "$src" ]; then
    echo "warning: '$s' not found in hora-core — skipping" >&2
    continue
  fi
  rm -rf "${DEST:?}/$s"
  mkdir -p "$DEST/$s"
  cp -R "$src/." "$DEST/$s/"
  echo "$s" >> "$manifest"
  echo "synced: $s"
done

echo "Done -> $DEST (generated; edit shared skills in hora-core, then re-run)."
